spring.application.name=parking
server.port=8083

spring.datasource.url=jdbc:postgresql://ep-polished-sky-apezvmdp-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_S5GLYb0XvZfj
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.jwt.secret=urbanpark-saas-secret-key-must-be-at-least-32-characters-long
app.jwt.expiration=900000
app.jwt.refresh-expiration=604800000